substitutions:
  _SERVICE_NAME: portfolio-web
  _REGION: us-central1
  _AR_REGION: us-central1
  _AR_REPOSITORY: portfolio-images
  _IMAGE_NAME: portfolio-web
  _PORTFOLIO_AGENT_BASE_URL: "https://portfolio-agent-399951936554.us-central1.run.app"
  _AGENT_REQUEST_TIMEOUT_MS: "30000"
  _PORTFOLIO_WEB_BASE_URL: "https://portfolio.caldasdev.store"
  _PORTFOLIO_WEB_SA: 399951936554-compute@developer.gserviceaccount.com
  _CONTACT_FROM_EMAIL: contato@caldasdev.store
  _CONTACT_TO_EMAIL: lucastere10@gmail.com

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA
      - -t
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:latest
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -ceu
      - |
        docker push "${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}"
        docker push "${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:latest"

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -ceu
      - |
        gcloud run deploy "${_SERVICE_NAME}" \
          --image="${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}" \
          --region="${_REGION}" \
          --platform=managed \
          --allow-unauthenticated \
          --service-account="${_PORTFOLIO_WEB_SA}" \
          --port=8080 \
          --update-env-vars="PORTFOLIO_AGENT_BASE_URL=${_PORTFOLIO_AGENT_BASE_URL}" \
          --update-env-vars="AGENT_REQUEST_TIMEOUT_MS=${_AGENT_REQUEST_TIMEOUT_MS}" \
          --update-env-vars="PORTFOLIO_WEB_BASE_URL=${_PORTFOLIO_WEB_BASE_URL}" \
          --update-env-vars="CONTACT_FROM_EMAIL=${_CONTACT_FROM_EMAIL}" \
          --update-env-vars="CONTACT_TO_EMAIL=${_CONTACT_TO_EMAIL}" \
          --update-secrets="RESEND_API_KEY=RESEND_API_KEY:latest"

images:
  - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA
  - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:latest

options:
  logging: CLOUD_LOGGING_ONLY
