substitutions:
  _SERVICE_NAME: portfolio
  _REGION: southamerica-east1
  _AR_REGION: southamerica-east1
  _AR_REPOSITORY: cloud-run
  _IMAGE_NAME: portfolio
  _TAG: latest

steps:
  - id: Build image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - .

  - id: Push image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:${_TAG}

  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8080"

images:
  - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY